name: Deploy Azure Function App

on:
  push:
    paths:
      - 'azure-functions/**'
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Azure Function App
    runs-on: ubuntu-latest
    env:
        AZURE_FUNCTIONAPP_NAME: ${{ secrets.FUNCTION_APP_FUNCTION_NAME }}
        AZURE_RESOURCE_GROUP: ${{ secrets.MAIN_RESOURCE_GROUP_NAME }}
        AZURE_REGION: ${{ secrets.AZURE_REGION }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r azure-functions/requirements.txt

      - name: 'Deploy to Azure Function App'
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './azure-functions' # path to your function app code
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # publish profile secret